-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity matrixmul_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    in_A_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    in_A_TVALID : IN STD_LOGIC;
    in_A_TREADY : OUT STD_LOGIC;
    out_C_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    out_C_TVALID : OUT STD_LOGIC;
    out_C_TREADY : IN STD_LOGIC );
end;


architecture behav of matrixmul_3 is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "matrixmul_3_matrixmul_3,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.923000,HLS_SYN_LAT=281,HLS_SYN_TPT=none,HLS_SYN_MEM=1,HLS_SYN_DSP=0,HLS_SYN_FF=2916,HLS_SYN_LUT=2071,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";

    signal ap_rst_n_inv : STD_LOGIC;
    signal input_A_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_A_ce0 : STD_LOGIC;
    signal input_A_we0 : STD_LOGIC;
    signal input_A_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_A_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_A_1_ce0 : STD_LOGIC;
    signal input_A_1_we0 : STD_LOGIC;
    signal input_A_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_A_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_A_2_ce0 : STD_LOGIC;
    signal input_A_2_we0 : STD_LOGIC;
    signal input_A_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_A_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_A_3_ce0 : STD_LOGIC;
    signal input_A_3_we0 : STD_LOGIC;
    signal input_A_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_A_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_A_4_ce0 : STD_LOGIC;
    signal input_A_4_we0 : STD_LOGIC;
    signal input_A_4_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_A_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_A_5_ce0 : STD_LOGIC;
    signal input_A_5_we0 : STD_LOGIC;
    signal input_A_5_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_A_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_A_6_ce0 : STD_LOGIC;
    signal input_A_6_we0 : STD_LOGIC;
    signal input_A_6_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_A_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_A_7_ce0 : STD_LOGIC;
    signal input_A_7_we0 : STD_LOGIC;
    signal input_A_7_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_B_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_B_ce0 : STD_LOGIC;
    signal input_B_we0 : STD_LOGIC;
    signal input_B_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_B_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_B_1_ce0 : STD_LOGIC;
    signal input_B_1_we0 : STD_LOGIC;
    signal input_B_1_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_B_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_B_2_ce0 : STD_LOGIC;
    signal input_B_2_we0 : STD_LOGIC;
    signal input_B_2_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_B_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_B_3_ce0 : STD_LOGIC;
    signal input_B_3_we0 : STD_LOGIC;
    signal input_B_3_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_B_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_B_4_ce0 : STD_LOGIC;
    signal input_B_4_we0 : STD_LOGIC;
    signal input_B_4_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_B_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_B_5_ce0 : STD_LOGIC;
    signal input_B_5_we0 : STD_LOGIC;
    signal input_B_5_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_B_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_B_6_ce0 : STD_LOGIC;
    signal input_B_6_we0 : STD_LOGIC;
    signal input_B_6_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal input_B_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal input_B_7_ce0 : STD_LOGIC;
    signal input_B_7_we0 : STD_LOGIC;
    signal input_B_7_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal output_C_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal output_C_ce0 : STD_LOGIC;
    signal output_C_we0 : STD_LOGIC;
    signal output_C_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_start : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_done : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_idle : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_ready : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_in_A_TREADY : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_start : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_done : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_idle : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_ready : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_in_A_TREADY : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_start : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_done : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_idle : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_ready : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_1_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_2_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_3_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_4_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_5_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_6_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_7_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_we0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_1_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_1_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_2_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_2_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_3_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_3_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_4_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_4_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_5_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_5_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_6_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_6_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_7_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_7_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_start : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_done : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_idle : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_ready : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TREADY : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_output_C_address0 : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_output_C_ce0 : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TVALID : STD_LOGIC;
    signal grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal out_C_TDATA_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal regslice_both_out_C_U_apdone_blk : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal regslice_both_in_A_U_apdone_blk : STD_LOGIC;
    signal in_A_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal in_A_TVALID_int_regslice : STD_LOGIC;
    signal in_A_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_in_A_U_ack_in : STD_LOGIC;
    signal out_C_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal out_C_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_out_C_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component matrixmul_3_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_A_TVALID : IN STD_LOGIC;
        input_A_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_ce0 : OUT STD_LOGIC;
        input_A_we0 : OUT STD_LOGIC;
        input_A_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_A_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_1_ce0 : OUT STD_LOGIC;
        input_A_1_we0 : OUT STD_LOGIC;
        input_A_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_A_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_2_ce0 : OUT STD_LOGIC;
        input_A_2_we0 : OUT STD_LOGIC;
        input_A_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_A_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_3_ce0 : OUT STD_LOGIC;
        input_A_3_we0 : OUT STD_LOGIC;
        input_A_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_A_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_4_ce0 : OUT STD_LOGIC;
        input_A_4_we0 : OUT STD_LOGIC;
        input_A_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_A_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_5_ce0 : OUT STD_LOGIC;
        input_A_5_we0 : OUT STD_LOGIC;
        input_A_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_A_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_6_ce0 : OUT STD_LOGIC;
        input_A_6_we0 : OUT STD_LOGIC;
        input_A_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_A_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_7_ce0 : OUT STD_LOGIC;
        input_A_7_we0 : OUT STD_LOGIC;
        input_A_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_A_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        in_A_TREADY : OUT STD_LOGIC );
    end component;


    component matrixmul_3_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        in_A_TVALID : IN STD_LOGIC;
        input_B_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_7_ce0 : OUT STD_LOGIC;
        input_B_7_we0 : OUT STD_LOGIC;
        input_B_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_B_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_6_ce0 : OUT STD_LOGIC;
        input_B_6_we0 : OUT STD_LOGIC;
        input_B_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_B_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_5_ce0 : OUT STD_LOGIC;
        input_B_5_we0 : OUT STD_LOGIC;
        input_B_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_B_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_4_ce0 : OUT STD_LOGIC;
        input_B_4_we0 : OUT STD_LOGIC;
        input_B_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_B_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_3_ce0 : OUT STD_LOGIC;
        input_B_3_we0 : OUT STD_LOGIC;
        input_B_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_B_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_2_ce0 : OUT STD_LOGIC;
        input_B_2_we0 : OUT STD_LOGIC;
        input_B_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_B_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_1_ce0 : OUT STD_LOGIC;
        input_B_1_we0 : OUT STD_LOGIC;
        input_B_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_B_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_ce0 : OUT STD_LOGIC;
        input_B_we0 : OUT STD_LOGIC;
        input_B_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        in_A_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        in_A_TREADY : OUT STD_LOGIC );
    end component;


    component matrixmul_3_matrixmul_3_Pipeline_loop1_loop2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_A_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_ce0 : OUT STD_LOGIC;
        input_A_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_A_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_1_ce0 : OUT STD_LOGIC;
        input_A_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_A_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_2_ce0 : OUT STD_LOGIC;
        input_A_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_A_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_3_ce0 : OUT STD_LOGIC;
        input_A_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_A_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_4_ce0 : OUT STD_LOGIC;
        input_A_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_A_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_5_ce0 : OUT STD_LOGIC;
        input_A_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_A_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_6_ce0 : OUT STD_LOGIC;
        input_A_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_A_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_A_7_ce0 : OUT STD_LOGIC;
        input_A_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        output_C_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        output_C_ce0 : OUT STD_LOGIC;
        output_C_we0 : OUT STD_LOGIC;
        output_C_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        input_B_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_ce0 : OUT STD_LOGIC;
        input_B_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_B_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_1_ce0 : OUT STD_LOGIC;
        input_B_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_B_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_2_ce0 : OUT STD_LOGIC;
        input_B_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_B_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_3_ce0 : OUT STD_LOGIC;
        input_B_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_B_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_4_ce0 : OUT STD_LOGIC;
        input_B_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_B_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_5_ce0 : OUT STD_LOGIC;
        input_B_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_B_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_6_ce0 : OUT STD_LOGIC;
        input_B_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        input_B_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
        input_B_7_ce0 : OUT STD_LOGIC;
        input_B_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matrixmul_3_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_C_TREADY : IN STD_LOGIC;
        output_C_address0 : OUT STD_LOGIC_VECTOR (5 downto 0);
        output_C_ce0 : OUT STD_LOGIC;
        output_C_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        out_C_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_C_TVALID : OUT STD_LOGIC );
    end component;


    component matrixmul_3_input_A_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matrixmul_3_output_C_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (5 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component matrixmul_3_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    input_A_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_A_address0,
        ce0 => input_A_ce0,
        we0 => input_A_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_d0,
        q0 => input_A_q0);

    input_A_1_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_A_1_address0,
        ce0 => input_A_1_ce0,
        we0 => input_A_1_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_d0,
        q0 => input_A_1_q0);

    input_A_2_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_A_2_address0,
        ce0 => input_A_2_ce0,
        we0 => input_A_2_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_d0,
        q0 => input_A_2_q0);

    input_A_3_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_A_3_address0,
        ce0 => input_A_3_ce0,
        we0 => input_A_3_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_d0,
        q0 => input_A_3_q0);

    input_A_4_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_A_4_address0,
        ce0 => input_A_4_ce0,
        we0 => input_A_4_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_d0,
        q0 => input_A_4_q0);

    input_A_5_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_A_5_address0,
        ce0 => input_A_5_ce0,
        we0 => input_A_5_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_d0,
        q0 => input_A_5_q0);

    input_A_6_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_A_6_address0,
        ce0 => input_A_6_ce0,
        we0 => input_A_6_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_d0,
        q0 => input_A_6_q0);

    input_A_7_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_A_7_address0,
        ce0 => input_A_7_ce0,
        we0 => input_A_7_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_d0,
        q0 => input_A_7_q0);

    input_B_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_B_address0,
        ce0 => input_B_ce0,
        we0 => input_B_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_d0,
        q0 => input_B_q0);

    input_B_1_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_B_1_address0,
        ce0 => input_B_1_ce0,
        we0 => input_B_1_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_d0,
        q0 => input_B_1_q0);

    input_B_2_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_B_2_address0,
        ce0 => input_B_2_ce0,
        we0 => input_B_2_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_d0,
        q0 => input_B_2_q0);

    input_B_3_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_B_3_address0,
        ce0 => input_B_3_ce0,
        we0 => input_B_3_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_d0,
        q0 => input_B_3_q0);

    input_B_4_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_B_4_address0,
        ce0 => input_B_4_ce0,
        we0 => input_B_4_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_d0,
        q0 => input_B_4_q0);

    input_B_5_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_B_5_address0,
        ce0 => input_B_5_ce0,
        we0 => input_B_5_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_d0,
        q0 => input_B_5_q0);

    input_B_6_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_B_6_address0,
        ce0 => input_B_6_ce0,
        we0 => input_B_6_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_d0,
        q0 => input_B_6_q0);

    input_B_7_U : component matrixmul_3_input_A_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => input_B_7_address0,
        ce0 => input_B_7_ce0,
        we0 => input_B_7_we0,
        d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_d0,
        q0 => input_B_7_q0);

    output_C_U : component matrixmul_3_output_C_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 64,
        AddressWidth => 6)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => output_C_address0,
        ce0 => output_C_ce0,
        we0 => output_C_we0,
        d0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_d0,
        q0 => output_C_q0);

    grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104 : component matrixmul_3_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_start,
        ap_done => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_done,
        ap_idle => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_idle,
        ap_ready => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_ready,
        in_A_TVALID => in_A_TVALID_int_regslice,
        input_A_address0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_address0,
        input_A_ce0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_ce0,
        input_A_we0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_we0,
        input_A_d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_d0,
        input_A_1_address0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_address0,
        input_A_1_ce0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_ce0,
        input_A_1_we0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_we0,
        input_A_1_d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_d0,
        input_A_2_address0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_address0,
        input_A_2_ce0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_ce0,
        input_A_2_we0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_we0,
        input_A_2_d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_d0,
        input_A_3_address0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_address0,
        input_A_3_ce0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_ce0,
        input_A_3_we0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_we0,
        input_A_3_d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_d0,
        input_A_4_address0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_address0,
        input_A_4_ce0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_ce0,
        input_A_4_we0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_we0,
        input_A_4_d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_d0,
        input_A_5_address0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_address0,
        input_A_5_ce0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_ce0,
        input_A_5_we0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_we0,
        input_A_5_d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_d0,
        input_A_6_address0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_address0,
        input_A_6_ce0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_ce0,
        input_A_6_we0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_we0,
        input_A_6_d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_d0,
        input_A_7_address0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_address0,
        input_A_7_ce0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_ce0,
        input_A_7_we0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_we0,
        input_A_7_d0 => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_d0,
        in_A_TDATA => in_A_TDATA_int_regslice,
        in_A_TREADY => grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_in_A_TREADY);

    grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118 : component matrixmul_3_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_start,
        ap_done => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_done,
        ap_idle => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_idle,
        ap_ready => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_ready,
        in_A_TVALID => in_A_TVALID_int_regslice,
        input_B_7_address0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_address0,
        input_B_7_ce0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_ce0,
        input_B_7_we0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_we0,
        input_B_7_d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_d0,
        input_B_6_address0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_address0,
        input_B_6_ce0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_ce0,
        input_B_6_we0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_we0,
        input_B_6_d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_d0,
        input_B_5_address0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_address0,
        input_B_5_ce0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_ce0,
        input_B_5_we0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_we0,
        input_B_5_d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_d0,
        input_B_4_address0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_address0,
        input_B_4_ce0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_ce0,
        input_B_4_we0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_we0,
        input_B_4_d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_d0,
        input_B_3_address0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_address0,
        input_B_3_ce0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_ce0,
        input_B_3_we0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_we0,
        input_B_3_d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_d0,
        input_B_2_address0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_address0,
        input_B_2_ce0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_ce0,
        input_B_2_we0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_we0,
        input_B_2_d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_d0,
        input_B_1_address0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_address0,
        input_B_1_ce0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_ce0,
        input_B_1_we0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_we0,
        input_B_1_d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_d0,
        input_B_address0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_address0,
        input_B_ce0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_ce0,
        input_B_we0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_we0,
        input_B_d0 => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_d0,
        in_A_TDATA => in_A_TDATA_int_regslice,
        in_A_TREADY => grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_in_A_TREADY);

    grp_matrixmul_3_Pipeline_loop1_loop2_fu_132 : component matrixmul_3_matrixmul_3_Pipeline_loop1_loop2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_start,
        ap_done => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_done,
        ap_idle => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_idle,
        ap_ready => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_ready,
        input_A_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_address0,
        input_A_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_ce0,
        input_A_q0 => input_A_q0,
        input_A_1_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_1_address0,
        input_A_1_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_1_ce0,
        input_A_1_q0 => input_A_1_q0,
        input_A_2_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_2_address0,
        input_A_2_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_2_ce0,
        input_A_2_q0 => input_A_2_q0,
        input_A_3_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_3_address0,
        input_A_3_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_3_ce0,
        input_A_3_q0 => input_A_3_q0,
        input_A_4_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_4_address0,
        input_A_4_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_4_ce0,
        input_A_4_q0 => input_A_4_q0,
        input_A_5_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_5_address0,
        input_A_5_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_5_ce0,
        input_A_5_q0 => input_A_5_q0,
        input_A_6_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_6_address0,
        input_A_6_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_6_ce0,
        input_A_6_q0 => input_A_6_q0,
        input_A_7_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_7_address0,
        input_A_7_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_7_ce0,
        input_A_7_q0 => input_A_7_q0,
        output_C_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_address0,
        output_C_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_ce0,
        output_C_we0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_we0,
        output_C_d0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_d0,
        input_B_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_address0,
        input_B_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_ce0,
        input_B_q0 => input_B_q0,
        input_B_1_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_1_address0,
        input_B_1_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_1_ce0,
        input_B_1_q0 => input_B_1_q0,
        input_B_2_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_2_address0,
        input_B_2_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_2_ce0,
        input_B_2_q0 => input_B_2_q0,
        input_B_3_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_3_address0,
        input_B_3_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_3_ce0,
        input_B_3_q0 => input_B_3_q0,
        input_B_4_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_4_address0,
        input_B_4_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_4_ce0,
        input_B_4_q0 => input_B_4_q0,
        input_B_5_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_5_address0,
        input_B_5_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_5_ce0,
        input_B_5_q0 => input_B_5_q0,
        input_B_6_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_6_address0,
        input_B_6_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_6_ce0,
        input_B_6_q0 => input_B_6_q0,
        input_B_7_address0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_7_address0,
        input_B_7_ce0 => grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_7_ce0,
        input_B_7_q0 => input_B_7_q0);

    grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153 : component matrixmul_3_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_start,
        ap_done => grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_done,
        ap_idle => grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_idle,
        ap_ready => grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_ready,
        out_C_TREADY => grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TREADY,
        output_C_address0 => grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_output_C_address0,
        output_C_ce0 => grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_output_C_ce0,
        output_C_q0 => output_C_q0,
        out_C_TDATA => grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TDATA,
        out_C_TVALID => grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TVALID);

    regslice_both_in_A_U : component matrixmul_3_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => in_A_TDATA,
        vld_in => in_A_TVALID,
        ack_in => regslice_both_in_A_U_ack_in,
        data_out => in_A_TDATA_int_regslice,
        vld_out => in_A_TVALID_int_regslice,
        ack_out => in_A_TREADY_int_regslice,
        apdone_blk => regslice_both_in_A_U_apdone_blk);

    regslice_both_out_C_U : component matrixmul_3_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => out_C_TDATA_int_regslice,
        vld_in => grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TVALID,
        ack_in => out_C_TREADY_int_regslice,
        data_out => out_C_TDATA,
        vld_out => regslice_both_out_C_U_vld_out,
        ack_out => out_C_TREADY,
        apdone_blk => regslice_both_out_C_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                    grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_ready = ap_const_logic_1)) then 
                    grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_ready = ap_const_logic_1)) then 
                    grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_ready = ap_const_logic_1)) then 
                    grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_ready = ap_const_logic_1)) then 
                    grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                out_C_TDATA_reg <= grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TDATA;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_done, grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_done, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_done, grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_done, ap_CS_fsm, ap_CS_fsm_state3, ap_CS_fsm_state5, ap_CS_fsm_state7, ap_CS_fsm_state9, regslice_both_out_C_U_apdone_blk, ap_CS_fsm_state10)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                if (((grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                if (((regslice_both_out_C_U_apdone_blk = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_ST_fsm_state10_blk_assign_proc : process(regslice_both_out_C_U_apdone_blk)
    begin
        if ((regslice_both_out_C_U_apdone_blk = ap_const_logic_1)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state1_blk <= ap_const_logic_0;
    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_done)
    begin
        if ((grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;

    ap_ST_fsm_state5_blk_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_done)
    begin
        if ((grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_fsm_state7_blk_assign_proc : process(grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_done)
    begin
        if ((grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_done)
    begin
        if ((grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_start <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_ap_start_reg;
    grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_start <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_ap_start_reg;
    grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_start <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_ap_start_reg;
    grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_start <= grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_ap_start_reg;
    grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TREADY <= (out_C_TREADY_int_regslice and ap_CS_fsm_state9);
    in_A_TREADY <= regslice_both_in_A_U_ack_in;

    in_A_TREADY_int_regslice_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_in_A_TREADY, grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_in_A_TREADY, ap_CS_fsm_state3, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            in_A_TREADY_int_regslice <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_in_A_TREADY;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            in_A_TREADY_int_regslice <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_in_A_TREADY;
        else 
            in_A_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    input_A_1_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_1_address0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_1_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_1_address0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_address0;
        else 
            input_A_1_address0 <= "XXX";
        end if; 
    end process;


    input_A_1_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_1_ce0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_1_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_1_ce0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_ce0;
        else 
            input_A_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_1_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_1_we0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_1_we0;
        else 
            input_A_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_2_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_2_address0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_2_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_2_address0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_address0;
        else 
            input_A_2_address0 <= "XXX";
        end if; 
    end process;


    input_A_2_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_2_ce0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_2_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_2_ce0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_ce0;
        else 
            input_A_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_2_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_2_we0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_2_we0;
        else 
            input_A_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_3_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_3_address0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_3_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_3_address0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_address0;
        else 
            input_A_3_address0 <= "XXX";
        end if; 
    end process;


    input_A_3_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_3_ce0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_3_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_3_ce0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_ce0;
        else 
            input_A_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_3_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_3_we0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_3_we0;
        else 
            input_A_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_4_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_4_address0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_4_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_4_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_4_address0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_address0;
        else 
            input_A_4_address0 <= "XXX";
        end if; 
    end process;


    input_A_4_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_4_ce0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_4_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_4_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_4_ce0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_ce0;
        else 
            input_A_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_4_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_4_we0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_4_we0;
        else 
            input_A_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_5_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_5_address0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_5_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_5_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_5_address0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_address0;
        else 
            input_A_5_address0 <= "XXX";
        end if; 
    end process;


    input_A_5_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_5_ce0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_5_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_5_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_5_ce0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_ce0;
        else 
            input_A_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_5_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_5_we0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_5_we0;
        else 
            input_A_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_6_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_6_address0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_6_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_6_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_6_address0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_address0;
        else 
            input_A_6_address0 <= "XXX";
        end if; 
    end process;


    input_A_6_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_6_ce0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_6_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_6_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_6_ce0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_ce0;
        else 
            input_A_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_6_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_6_we0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_6_we0;
        else 
            input_A_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_7_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_7_address0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_7_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_7_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_7_address0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_address0;
        else 
            input_A_7_address0 <= "XXX";
        end if; 
    end process;


    input_A_7_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_7_ce0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_7_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_7_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_7_ce0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_ce0;
        else 
            input_A_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_7_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_7_we0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_7_we0;
        else 
            input_A_7_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_address0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_address0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_address0;
        else 
            input_A_address0 <= "XXX";
        end if; 
    end process;


    input_A_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_ce0, ap_CS_fsm_state3, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_A_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_A_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_ce0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_ce0;
        else 
            input_A_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_A_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_we0, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_A_we0 <= grp_matrixmul_3_Pipeline_loop_input_A1_loop_input_A2_fu_104_input_A_we0;
        else 
            input_A_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_1_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_1_address0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_1_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_1_address0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_address0;
        else 
            input_B_1_address0 <= "XXX";
        end if; 
    end process;


    input_B_1_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_1_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_1_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_1_ce0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_ce0;
        else 
            input_B_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_1_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_1_we0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_1_we0;
        else 
            input_B_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_2_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_2_address0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_2_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_2_address0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_address0;
        else 
            input_B_2_address0 <= "XXX";
        end if; 
    end process;


    input_B_2_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_2_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_2_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_2_ce0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_ce0;
        else 
            input_B_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_2_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_2_we0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_2_we0;
        else 
            input_B_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_3_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_3_address0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_3_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_3_address0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_address0;
        else 
            input_B_3_address0 <= "XXX";
        end if; 
    end process;


    input_B_3_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_3_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_3_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_3_ce0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_ce0;
        else 
            input_B_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_3_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_3_we0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_3_we0;
        else 
            input_B_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_4_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_4_address0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_4_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_4_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_4_address0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_address0;
        else 
            input_B_4_address0 <= "XXX";
        end if; 
    end process;


    input_B_4_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_4_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_4_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_4_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_4_ce0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_ce0;
        else 
            input_B_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_4_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_4_we0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_4_we0;
        else 
            input_B_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_5_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_5_address0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_5_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_5_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_5_address0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_address0;
        else 
            input_B_5_address0 <= "XXX";
        end if; 
    end process;


    input_B_5_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_5_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_5_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_5_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_5_ce0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_ce0;
        else 
            input_B_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_5_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_5_we0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_5_we0;
        else 
            input_B_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_6_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_6_address0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_6_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_6_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_6_address0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_address0;
        else 
            input_B_6_address0 <= "XXX";
        end if; 
    end process;


    input_B_6_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_6_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_6_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_6_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_6_ce0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_ce0;
        else 
            input_B_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_6_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_6_we0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_6_we0;
        else 
            input_B_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_7_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_7_address0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_7_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_7_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_7_address0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_address0;
        else 
            input_B_7_address0 <= "XXX";
        end if; 
    end process;


    input_B_7_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_7_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_7_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_7_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_7_ce0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_ce0;
        else 
            input_B_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_7_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_7_we0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_7_we0;
        else 
            input_B_7_we0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_address0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_address0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_address0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_address0;
        else 
            input_B_address0 <= "XXX";
        end if; 
    end process;


    input_B_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_ce0, grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_ce0, ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_B_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_input_B_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_ce0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_ce0;
        else 
            input_B_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    input_B_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_we0, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            input_B_we0 <= grp_matrixmul_3_Pipeline_loop_input_B1_loop_input_B2_fu_118_input_B_we0;
        else 
            input_B_we0 <= ap_const_logic_0;
        end if; 
    end process;


    out_C_TDATA_int_regslice_assign_proc : process(grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TDATA, grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TVALID, ap_CS_fsm_state9, out_C_TDATA_reg)
    begin
        if (((grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            out_C_TDATA_int_regslice <= grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_out_C_TDATA;
        else 
            out_C_TDATA_int_regslice <= out_C_TDATA_reg;
        end if; 
    end process;

    out_C_TVALID <= regslice_both_out_C_U_vld_out;

    output_C_address0_assign_proc : process(grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_address0, grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_output_C_address0, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_C_address0 <= grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_output_C_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            output_C_address0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_address0;
        else 
            output_C_address0 <= "XXXXXX";
        end if; 
    end process;


    output_C_ce0_assign_proc : process(grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_ce0, grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_output_C_ce0, ap_CS_fsm_state7, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_C_ce0 <= grp_matrixmul_3_Pipeline_loop_output_C1_loop_output_C2_fu_153_output_C_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            output_C_ce0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_ce0;
        else 
            output_C_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    output_C_we0_assign_proc : process(grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_we0, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            output_C_we0 <= grp_matrixmul_3_Pipeline_loop1_loop2_fu_132_output_C_we0;
        else 
            output_C_we0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
