# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Samarth/Desktop/IIIT_Intern/Tutorial_matrix/Vivado_files/demo_matrix/demo_matrix.srcs/sources_1/bd/matrix/ip/matrix_zynq_ultra_ps_e_0_0/matrix_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'matrix_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Samarth/Desktop/IIIT_Intern/Tutorial_matrix/Vivado_files/demo_matrix/demo_matrix.gen/sources_1/bd/matrix/ip/matrix_zynq_ultra_ps_e_0_0/matrix_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Samarth/Desktop/IIIT_Intern/Tutorial_matrix/Vivado_files/demo_matrix/demo_matrix.gen/sources_1/bd/matrix/ip/matrix_zynq_ultra_ps_e_0_0/matrix_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Samarth/Desktop/IIIT_Intern/Tutorial_matrix/Vivado_files/demo_matrix/demo_matrix.srcs/sources_1/bd/matrix/ip/matrix_zynq_ultra_ps_e_0_0/matrix_zynq_ultra_ps_e_0_0.xci
# IP: The module: 'matrix_zynq_ultra_ps_e_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Samarth/Desktop/IIIT_Intern/Tutorial_matrix/Vivado_files/demo_matrix/demo_matrix.gen/sources_1/bd/matrix/ip/matrix_zynq_ultra_ps_e_0_0/matrix_zynq_ultra_ps_e_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Samarth/Desktop/IIIT_Intern/Tutorial_matrix/Vivado_files/demo_matrix/demo_matrix.gen/sources_1/bd/matrix/ip/matrix_zynq_ultra_ps_e_0_0/matrix_zynq_ultra_ps_e_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'matrix_zynq_ultra_ps_e_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
