// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module operator_mul (
        ap_clk,
        ap_rst,
        x_complex_float_re_read,
        x_complex_float_im_read,
        rhs_re_read,
        rhs_im_read,
        ap_return_0,
        ap_return_1,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] x_complex_float_re_read;
input  [31:0] x_complex_float_im_read;
input  [31:0] rhs_re_read;
input  [31:0] rhs_im_read;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
input   ap_ce;

reg[31:0] ap_return_0;
reg[31:0] ap_return_1;

wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_pp0_stage0_11001;
wire   [31:0] grp_fu_44_p2;
reg   [31:0] m1_reg_104;
wire   [31:0] grp_fu_50_p2;
reg   [31:0] m2_reg_109;
wire   [31:0] grp_fu_56_p2;
reg   [31:0] m3_reg_114;
wire   [31:0] grp_fu_62_p2;
reg   [31:0] m4_reg_119;
wire    ap_block_pp0_stage0;
wire   [31:0] grp_fu_36_p2;
wire   [31:0] grp_fu_40_p2;
reg    grp_fu_36_ce;
reg    grp_fu_40_ce;
reg    grp_fu_44_ce;
reg    grp_fu_50_ce;
reg    grp_fu_56_ce;
reg    grp_fu_62_ce;
reg    ap_ce_reg;
reg   [31:0] x_complex_float_re_read_int_reg;
reg   [31:0] x_complex_float_im_read_int_reg;
reg   [31:0] rhs_re_read_int_reg;
reg   [31:0] rhs_im_read_int_reg;
reg   [31:0] ap_return_0_int_reg;
reg   [31:0] ap_return_1_int_reg;

MUSIC_top_fsub_32kbM #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
MUSIC_top_fsub_32kbM_U295(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(m1_reg_104),
    .din1(m2_reg_109),
    .ce(grp_fu_36_ce),
    .dout(grp_fu_36_p2)
);

MUSIC_top_fadd_32lbW #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
MUSIC_top_fadd_32lbW_U296(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(m3_reg_114),
    .din1(m4_reg_119),
    .ce(grp_fu_40_ce),
    .dout(grp_fu_40_p2)
);

MUSIC_top_fmul_32mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
MUSIC_top_fmul_32mb6_U297(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_re_read_int_reg),
    .din1(x_complex_float_re_read_int_reg),
    .ce(grp_fu_44_ce),
    .dout(grp_fu_44_p2)
);

MUSIC_top_fmul_32mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
MUSIC_top_fmul_32mb6_U298(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_im_read_int_reg),
    .din1(x_complex_float_im_read_int_reg),
    .ce(grp_fu_50_ce),
    .dout(grp_fu_50_p2)
);

MUSIC_top_fmul_32mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
MUSIC_top_fmul_32mb6_U299(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_im_read_int_reg),
    .din1(x_complex_float_re_read_int_reg),
    .ce(grp_fu_56_ce),
    .dout(grp_fu_56_p2)
);

MUSIC_top_fmul_32mb6 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
MUSIC_top_fmul_32mb6_U300(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(rhs_re_read_int_reg),
    .din1(x_complex_float_im_read_int_reg),
    .ce(grp_fu_62_ce),
    .dout(grp_fu_62_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= grp_fu_36_p2;
        ap_return_1_int_reg <= grp_fu_40_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        m1_reg_104 <= grp_fu_44_p2;
        m2_reg_109 <= grp_fu_50_p2;
        m3_reg_114 <= grp_fu_56_p2;
        m4_reg_119 <= grp_fu_62_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        rhs_im_read_int_reg <= rhs_im_read;
        rhs_re_read_int_reg <= rhs_re_read;
        x_complex_float_im_read_int_reg <= x_complex_float_im_read;
        x_complex_float_re_read_int_reg <= x_complex_float_re_read;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = grp_fu_36_p2;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = grp_fu_40_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_36_ce = 1'b1;
    end else begin
        grp_fu_36_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_40_ce = 1'b1;
    end else begin
        grp_fu_40_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_44_ce = 1'b1;
    end else begin
        grp_fu_44_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_50_ce = 1'b1;
    end else begin
        grp_fu_50_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_56_ce = 1'b1;
    end else begin
        grp_fu_56_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_62_ce = 1'b1;
    end else begin
        grp_fu_62_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

endmodule //operator_mul
